In [1]:
# importing the needed packets.
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.impute import KNNImputer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    precision_score,
    recall_score,
    make_scorer,
    classification_report,
    ConfusionMatrixDisplay
)
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris

from sklearn import tree
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier

import xgboost as xgb

In [5]:
# Loading in the data with , as a delimiter to properly get the data frame loaded.
the_weather_data = pd.read_csv("../the_weather_data.csv", delimiter=',')

pd.set_option('display.max_columns', 20)

In [6]:
the_weather_data

,clouds,datetime,dewpt,dhi,dni,ghi,max_dhi,max_dni,max_ghi,max_temp,...,solar_rad,t_dhi,t_dni,t_ghi,t_solar_rad,temp,ts,wind_dir,wind_gust_spd,wind_spd
0,75,2023-11-08,4.7,16,142,39,64,575,192,8.0,...,4,390,3414,943,98,5.4,1699398000,115,6.8,2.0
1,88,2023-11-09,5.2,16,139,38,64,569,188,8.0,...,4,383,3338,910,91,6.1,1699484400,119,10.0,3.0
2,91,2023-11-10,6.8,16,136,37,63,564,183,9.0,...,4,375,3261,877,88,7.6,1699570800,143,8.4,2.1
3,70,2023-11-11,5.6,15,133,35,62,558,178,8.0,...,32,367,3183,845,775,6.4,1699657200,111,5.2,1.6
4,84,2023-11-12,2.9,15,129,34,62,552,174,6.0,...,4,359,3105,815,97,3.7,1699743600,300,9.6,3.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,9,2024-08-29,13.0,45,378,216,104,832,629,24.0,...,215,1090,9072,5182,5154,18.6,1724882400,120,9.8,4.4
296,33,2024-08-30,15.4,45,375,213,104,831,624,20.0,...,159,1081,9001,5111,3806,17.9,1724968800,186,6.2,2.7
297,1,2024-08-31,9.9,45,372,210,103,829,618,20.0,...,210,1072,8928,5040,5040,15.5,1725055200,265,8.0,3.9
298,45,2024-09-01,8.1,44,369,207,103,827,613,17.0,...,183,1062,8853,4969,4381,12.9,1725141600,268,4.5,2.7
299,39,2024-09-02,11.6,44,366,204,103,826,607,17.0,...,195,1053,8777,4898,4679,13.3,1725228000,188,4.7,2.4

In [7]:
the_weather_data.drop(columns=['dhi','dni','ghi','max_dhi','max_dni','max_ghi','max_temp','wind_dir','t_solar_rad','datetime','dewpt'], inplace=True)

In [9]:
the_weather_data.drop(columns=['max_uv','max_wind_dir','snow_depth','max_wind_spd_ts','min_temp_ts'], inplace=True)

In [11]:
the_weather_data
the_weather_data.drop(columns=['snow','revision_status'], inplace=True)

In [12]:
the_weather_data

,clouds,max_temp_ts,max_wind_spd,min_temp,revision_status,snow,solar_rad,temp,wind_gust_spd,wind_spd
0,75,1699452000,3.2,3.0,final,0.0,4,5.4,6.8,2.0
1,88,1699560000,5.2,3.0,final,0.0,4,6.1,10.0,3.0
2,91,1699614000,3.2,5.0,final,0.0,4,7.6,8.4,2.1
3,70,1699704000,2.5,5.0,final,0.0,32,6.4,5.2,1.6
4,84,1699743600,4.4,2.0,final,0.0,4,3.7,9.6,3.6
...,...,...,...,...,...,...,...,...,...,...
295,9,1724936400,8.1,12.0,interim,0.0,215,18.6,9.8,4.4
296,33,1725004800,5.4,13.0,interim,0.0,159,17.9,6.2,2.7
297,1,1725109200,6.8,12.0,interim,0.0,210,15.5,8.0,3.9
298,45,1725195600,4.1,10.0,interim,0.0,183,12.9,4.5,2.7
299,39,1725289200,4.2,12.0,interim,0.0,195,13.3,4.7,2.4

In [13]:
the_weather_data.to_csv('The_cleaned_weather_data.csv', index=False)